import mysql from 'mysql2/promise';
import bcrypt from 'bcryptjs';
import dotenv from 'dotenv';
import { v4 as uuidv4 } from 'uuid';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
dotenv.config({ path: resolve(__dirname, '../../.env') });

const words = [
  { word: 'ubiquitous', ipa: '/juːˈbɪk.wɪ.təs/', marathi: 'सर्वव्यापी', hindi: 'सर्वव्यापी', english: 'Present, appearing, or found everywhere', synonyms: ['omnipresent', 'universal', 'pervasive'], antonyms: ['rare', 'scarce'], root: 'Latin "ubique" meaning everywhere', family: ['ubiquity', 'ubiquitously'], pos: 'adjective', difficulty: 'advanced', category: 'general', examples: ['Smartphones have become ubiquitous in modern society.', 'The ubiquitous coffee shop can be found on every corner.'] },
  { word: 'eloquent', ipa: '/ˈel.ə.kwənt/', marathi: 'वाक्पटू', hindi: 'वाक्पटु', english: 'Fluent or persuasive in speaking or writing', synonyms: ['articulate', 'fluent', 'expressive'], antonyms: ['inarticulate', 'hesitant'], root: 'Latin "eloquent-" meaning to speak out', family: ['eloquence', 'eloquently'], pos: 'adjective', difficulty: 'advanced', category: 'general', examples: ['She gave an eloquent speech at the conference.', 'His eloquent writing style captivated readers.'] },
  { word: 'resilient', ipa: '/rɪˈzɪl.i.ənt/', marathi: 'लवचिक', hindi: 'लचीला', english: 'Able to withstand or recover quickly from difficult conditions', synonyms: ['tough', 'adaptable', 'flexible'], antonyms: ['fragile', 'vulnerable'], root: 'Latin "resilire" meaning to leap back', family: ['resilience', 'resiliently'], pos: 'adjective', difficulty: 'intermediate', category: 'general', examples: ['Children are remarkably resilient.', 'The resilient economy recovered quickly.'] },
  { word: 'innovate', ipa: '/ˈɪn.ə.veɪt/', marathi: 'नवनिर्माण करणे', hindi: 'नवाचार करना', english: 'Make changes in something established by introducing new methods or ideas', synonyms: ['pioneer', 'introduce', 'revolutionize'], antonyms: ['copy', 'imitate'], root: 'Latin "innovare" meaning to renew', family: ['innovation', 'innovative', 'innovator'], pos: 'verb', difficulty: 'intermediate', category: 'technical', techCategory: 'general', examples: ['Companies must innovate to stay competitive.', 'The team innovated a new approach to solve the problem.'] },
  { word: 'deploy', ipa: '/dɪˈplɔɪ/', marathi: 'तैनात करणे', hindi: 'तैनात करना', english: 'To bring resources into effective action; to install and run software', synonyms: ['implement', 'install', 'launch'], antonyms: ['withdraw', 'remove'], root: 'French "déployer" meaning to unfold', family: ['deployment', 'deployable'], pos: 'verb', difficulty: 'intermediate', category: 'technical', techCategory: 'devops', examples: ['We will deploy the new version tomorrow.', 'The team deployed the application to production.'] },
  { word: 'scalable', ipa: '/ˈskeɪ.lə.bəl/', marathi: 'विस्तारणीय', hindi: 'स्केलेबल', english: 'Able to be changed in size or scale; capable of being expanded', synonyms: ['expandable', 'adaptable', 'flexible'], antonyms: ['limited', 'fixed'], root: 'Latin "scala" meaning ladder', family: ['scale', 'scalability'], pos: 'adjective', difficulty: 'intermediate', category: 'technical', techCategory: 'architecture', examples: ['The architecture needs to be scalable.', 'We built a scalable cloud solution.'] },
  { word: 'algorithm', ipa: '/ˈæl.ɡə.rɪð.əm/', marathi: 'अल्गोरिदम', hindi: 'एल्गोरिथ्म', english: 'A process or set of rules to be followed in calculations or problem-solving', synonyms: ['procedure', 'process', 'methodology'], antonyms: [], root: 'Arabic "al-Khwārizmī" from mathematician', family: ['algorithmic'], pos: 'noun', difficulty: 'advanced', category: 'technical', techCategory: 'ai', examples: ['The algorithm sorts data efficiently.', 'Machine learning algorithms require large datasets.'] },
  { word: 'database', ipa: '/ˈdeɪ.tə.beɪs/', marathi: 'डेटाबेस', hindi: 'डेटाबेस', english: 'A structured set of data held in a computer', synonyms: ['repository', 'storage', 'archive'], antonyms: [], root: 'Modern English', family: ['databases'], pos: 'noun', difficulty: 'beginner', category: 'technical', techCategory: 'backend', examples: ['The database stores all user information.', 'We need to optimize our database queries.'] },
  { word: 'container', ipa: '/kənˈteɪ.nər/', marathi: 'कंटेनर', hindi: 'कंटेनर', english: 'A standardized unit of software that packages code and dependencies', synonyms: ['package', 'bundle'], antonyms: [], root: 'Latin "continere" meaning to hold together', family: ['contain', 'containerize'], pos: 'noun', difficulty: 'intermediate', category: 'technical', techCategory: 'devops', examples: ['Docker containers revolutionized deployment.', 'Each microservice runs in its own container.'] },
  { word: 'endpoint', ipa: '/ˈend.pɔɪnt/', marathi: 'एंडपॉइंट', hindi: 'एंडपॉइंट', english: 'A URL or API entry point in web services', synonyms: ['API endpoint', 'route', 'URL'], antonyms: [], root: 'Modern English', family: ['endpoints'], pos: 'noun', difficulty: 'intermediate', category: 'technical', techCategory: 'backend', examples: ['The API endpoint returns JSON data.', 'Create a new endpoint for user registration.'] },
  { word: 'abandon', ipa: '/əˈbæn.dən/', marathi: 'सोडून देणे', hindi: 'छोड़ देना', english: 'To leave behind or give up completely', synonyms: ['desert', 'forsake', 'relinquish'], antonyms: ['keep', 'maintain', 'retain'], root: 'Old French "abandoner"', family: ['abandoned', 'abandonment'], pos: 'verb', difficulty: 'beginner', category: 'general', examples: ['They had to abandon the project.', 'Never abandon your dreams.'] },
  { word: 'benefit', ipa: '/ˈben.ɪ.fɪt/', marathi: 'फायदा', hindi: 'लाभ', english: 'An advantage or profit gained from something', synonyms: ['advantage', 'gain', 'profit'], antonyms: ['disadvantage', 'loss'], root: 'Latin "benefactum" meaning good deed', family: ['beneficial', 'beneficiary'], pos: 'noun', difficulty: 'beginner', category: 'general', examples: ['Exercise has many health benefits.', 'The new policy will benefit everyone.'] },
  { word: 'collaborate', ipa: '/kəˈlæb.ə.reɪt/', marathi: 'सहकार्य करणे', hindi: 'सहयोग करना', english: 'To work jointly on an activity or project', synonyms: ['cooperate', 'team up', 'work together'], antonyms: ['compete', 'work alone'], root: 'Latin "collaborare" meaning to labor together', family: ['collaboration', 'collaborative', 'collaborator'], pos: 'verb', difficulty: 'intermediate', category: 'general', examples: ['Teams should collaborate effectively.', 'We collaborated on the research paper.'] },
  { word: 'efficient', ipa: '/ɪˈfɪʃ.ənt/', marathi: 'कार्यक्षम', hindi: 'कुशल', english: 'Achieving maximum productivity with minimum wasted effort', synonyms: ['productive', 'effective', 'streamlined'], antonyms: ['inefficient', 'wasteful'], root: 'Latin "efficient-" meaning accomplishing', family: ['efficiency', 'efficiently'], pos: 'adjective', difficulty: 'intermediate', category: 'general', examples: ['This is a very efficient process.', 'We need more efficient solutions.'] },
  { word: 'implement', ipa: '/ˈɪm.plɪ.ment/', marathi: 'अंमलबजावणी करणे', hindi: 'कार्यान्वित करना', english: 'To put a decision or plan into effect', synonyms: ['execute', 'apply', 'enforce'], antonyms: ['ignore', 'neglect'], root: 'Latin "implementum" meaning a filling up', family: ['implementation', 'implementable'], pos: 'verb', difficulty: 'intermediate', category: 'technical', examples: ['We will implement the new system next month.', 'The developer implemented the feature.'] },
  { word: 'optimize', ipa: '/ˈɒp.tɪ.maɪz/', marathi: 'ऑप्टिमाइझ करणे', hindi: 'अनुकूलित करना', english: 'To make the best or most effective use of a resource', synonyms: ['improve', 'enhance', 'streamline'], antonyms: ['worsen', 'degrade'], root: 'Latin "optimus" meaning best', family: ['optimization', 'optimal', 'optimum'], pos: 'verb', difficulty: 'intermediate', category: 'technical', examples: ['We need to optimize the database queries.', 'The algorithm was optimized for speed.'] },
  { word: 'architecture', ipa: '/ˈɑːr.kɪ.tek.tʃər/', marathi: 'आर्किटेक्चर', hindi: 'आर्किटेक्चर', english: 'The fundamental structure of a system', synonyms: ['structure', 'framework', 'design'], antonyms: [], root: 'Greek "arkhitekton" meaning master builder', family: ['architect', 'architectural'], pos: 'noun', difficulty: 'advanced', category: 'technical', techCategory: 'architecture', examples: ['The microservices architecture improved scalability.', 'System architecture must be well-planned.'] },
  { word: 'agile', ipa: '/ˈædʒ.aɪl/', marathi: 'चपळ', hindi: 'फुर्तीला', english: 'A method of project management that emphasizes flexibility and collaboration', synonyms: ['flexible', 'adaptive', 'responsive'], antonyms: ['rigid', 'inflexible'], root: 'Latin "agilis" meaning nimble', family: ['agility'], pos: 'adjective', difficulty: 'intermediate', category: 'technical', techCategory: 'general', examples: ['The team follows agile methodology.', 'Agile development enables quick iterations.'] },
  { word: 'synergy', ipa: '/ˈsɪn.ər.dʒi/', marathi: 'समन्वय', hindi: 'सहक्रिया', english: 'The interaction of elements that produces a combined effect greater than the sum of their separate effects', synonyms: ['cooperation', 'collaboration', 'partnership'], antonyms: ['conflict', 'division'], root: 'Greek "synergos" meaning working together', family: ['synergistic', 'synergize'], pos: 'noun', difficulty: 'advanced', category: 'general', examples: ['The team created a powerful synergy.', 'Cross-departmental synergy drives innovation.'] },
  { word: 'paradigm', ipa: '/ˈpær.ə.daɪm/', marathi: 'प्रतिमान', hindi: 'प्रतिमान', english: 'A typical example or pattern of something; a model', synonyms: ['model', 'pattern', 'framework'], antonyms: [], root: 'Greek "paradeigma" meaning pattern', family: ['paradigmatic'], pos: 'noun', difficulty: 'advanced', category: 'general', examples: ['This represents a new paradigm in computing.', 'The paradigm shifted towards cloud-native development.'] },
  { word: 'persistent', ipa: '/pərˈsɪs.tənt/', marathi: 'सातत्यपूर्ण', hindi: 'दृढ़', english: 'Continuing firmly in a course of action despite difficulty', synonyms: ['determined', 'tenacious', 'steadfast'], antonyms: ['inconsistent', 'irresolute'], root: 'Latin "persistere" meaning to continue steadfastly', family: ['persistence', 'persistently'], pos: 'adjective', difficulty: 'intermediate', category: 'general', examples: ['She was persistent in her efforts.', 'Persistent storage retains data after restart.'] },
  { word: 'proactive', ipa: '/prəʊˈæk.tɪv/', marathi: 'सक्रिय', hindi: 'सक्रिय', english: 'Acting in advance to deal with expected difficulties', synonyms: ['initiative', 'forward-looking', 'preventive'], antonyms: ['reactive', 'passive'], root: 'Modern English', family: ['proactivity', 'proactively'], pos: 'adjective', difficulty: 'intermediate', category: 'general', examples: ['Take a proactive approach to learning.', 'Proactive monitoring prevents system failures.'] },
  { word: 'robust', ipa: '/rəʊˈbʌst/', marathi: 'मजबूत', hindi: 'मजबूत', english: 'Strong and healthy; vigorous; resilient', synonyms: ['strong', 'sturdy', 'resilient'], antonyms: ['weak', 'fragile'], root: 'Latin "robustus" meaning firm', family: ['robustness', 'robustly'], pos: 'adjective', difficulty: 'intermediate', category: 'general', examples: ['The system has robust security measures.', 'A robust solution handles edge cases well.'] },
  { word: 'strategy', ipa: '/ˈstræt.ə.dʒi/', marathi: 'रणनीती', hindi: 'रणनीति', english: 'A plan of action designed to achieve a long-term goal', synonyms: ['plan', 'approach', 'tactic'], antonyms: [], root: 'Greek "strategia" meaning generalship', family: ['strategic', 'strategically', 'strategist'], pos: 'noun', difficulty: 'intermediate', category: 'general', examples: ['We need a clear marketing strategy.', 'The learning strategy focuses on consistency.'] },
  { word: 'transparent', ipa: '/trænˈspær.ənt/', marathi: 'पारदर्शक', hindi: 'पारदर्शी', english: 'Easy to perceive or detect; open and honest', synonyms: ['clear', 'obvious', 'candid'], antonyms: ['opaque', 'unclear', 'secretive'], root: 'Latin "transparens" meaning shining through', family: ['transparency', 'transparently'], pos: 'adjective', difficulty: 'intermediate', category: 'general', examples: ['The process should be transparent to users.', 'Transparent communication builds trust.'] },
  { word: 'versatile', ipa: '/ˈvɜːr.sə.taɪl/', marathi: 'बहुमुखी', hindi: 'बहुमुखी', english: 'Able to adapt or be adapted to many different functions', synonyms: ['adaptable', 'flexible', 'multipurpose'], antonyms: ['limited', 'inflexible'], root: 'Latin "versatilis" meaning capable of turning', family: ['versatility'], pos: 'adjective', difficulty: 'intermediate', category: 'general', examples: ['She is a versatile developer.', 'This tool is highly versatile.'] },
  { word: 'advocate', ipa: '/ˈæd.və.keɪt/', marathi: 'समर्थन करणे', hindi: 'समर्थन करना', english: 'To publicly recommend or support a cause or policy', synonyms: ['support', 'promote', 'champion'], antonyms: ['oppose', 'criticize'], root: 'Latin "advocatus" meaning summoned to give evidence', family: ['advocacy', 'advocator'], pos: 'verb', difficulty: 'intermediate', category: 'general', examples: ['He advocates for better education.', 'She advocated for the new policy.'] },
  { word: 'benchmark', ipa: '/ˈbentʃ.mɑːrk/', marathi: 'बेंचमार्क', hindi: 'बेंचमार्क', english: 'A standard against which things may be compared', synonyms: ['standard', 'yardstick', 'criterion'], antonyms: [], root: 'Modern English', family: ['benchmarking'], pos: 'noun', difficulty: 'intermediate', category: 'technical', techCategory: 'general', examples: ['We need to set a performance benchmark.', 'Benchmark tests showed significant improvement.'] },
  { word: 'comprehensive', ipa: '/ˌkɒm.prɪˈhen.sɪv/', marathi: 'सर्वसमावेशक', hindi: 'व्यापक', english: 'Including all or nearly all elements of something', synonyms: ['complete', 'thorough', 'exhaustive'], antonyms: ['incomplete', 'partial'], root: 'Latin "comprehendere" meaning to grasp', family: ['comprehension', 'comprehensively'], pos: 'adjective', difficulty: 'intermediate', category: 'general', examples: ['The report provides a comprehensive analysis.', 'A comprehensive testing strategy is essential.'] },
  { word: 'deprecated', ipa: '/ˈdep.rə.keɪ.tɪd/', marathi: 'नापसंत', hindi: 'अप्रचलित', english: 'No longer recommended for use; obsolete', synonyms: ['obsolete', 'outdated', 'discontinued'], antonyms: ['current', 'supported'], root: 'Latin "deprecatus" meaning prayed against', family: ['deprecate', 'deprecation'], pos: 'adjective', difficulty: 'advanced', category: 'technical', techCategory: 'general', examples: ['The API method has been deprecated.', 'Avoid using deprecated functions.'] },
  { word: 'enterprise', ipa: '/ˈen.tər.praɪz/', marathi: 'उद्योग', hindi: 'उद्यम', english: 'A business or company; a project or undertaking', synonyms: ['business', 'corporation', 'venture'], antonyms: [], root: 'French "entreprise" meaning undertaking', family: ['enterprising'], pos: 'noun', difficulty: 'intermediate', category: 'technical', techCategory: 'general', examples: ['Enterprise applications require high security.', 'The enterprise scaled to thousands of users.'] },
  { word: 'infrastructure', ipa: '/ˈɪn.frə.strʌk.tʃər/', marathi: 'पायाभूत सुविधा', hindi: 'बुनियादी ढांचा', english: 'The basic physical and organizational structures needed for operation', synonyms: ['framework', 'foundation', 'structure'], antonyms: [], root: 'Latin "infra" meaning below + "structura"', family: ['infrastructural'], pos: 'noun', difficulty: 'advanced', category: 'technical', techCategory: 'devops', examples: ['Cloud infrastructure enables global scale.', 'IT infrastructure must be reliable.'] },
  { word: 'leverage', ipa: '/ˈlev.ər.ɪdʒ/', marathi: 'लाभ घेणे', hindi: 'लाभ उठाना', english: 'To use something to maximum advantage', synonyms: ['utilize', 'exploit', 'capitalize'], antonyms: ['underuse', 'waste'], root: 'French "levier" meaning to lift', family: ['leveraged', 'leveraging'], pos: 'verb', difficulty: 'intermediate', category: 'general', examples: ['Leverage your strengths to succeed.', 'We should leverage existing resources.'] },
  { word: 'mitigate', ipa: '/ˈmɪt.ɪ.ɡeɪt/', marathi: 'कमी करणे', hindi: 'कम करना', english: 'To make less severe, serious, or painful', synonyms: ['alleviate', 'reduce', 'lessen'], antonyms: ['aggravate', 'worsen'], root: 'Latin "mitigatus" meaning to soften', family: ['mitigation', 'mitigating'], pos: 'verb', difficulty: 'advanced', category: 'general', examples: ['We need to mitigate the risks.', 'Effective measures mitigate the impact.'] },
  { word: 'refactor', ipa: '/riːˈfæk.tər/', marathi: 'रिफॅक्टर करणे', hindi: 'रीफैक्टर करना', english: 'To restructure existing code without changing its external behavior', synonyms: ['restructure', 'reorganize', 'improve'], antonyms: ['break', 'complicate'], root: 'Modern English', family: ['refactoring', 'refactored'], pos: 'verb', difficulty: 'intermediate', category: 'technical', techCategory: 'backend', examples: ['We should refactor this legacy code.', 'Regular refactoring improves code quality.'] },
  { word: 'troubleshoot', ipa: '/ˈtrʌb.əl.ʃuːt/', marathi: 'समस्या सोडवणे', hindi: 'समस्या निवारण', english: 'To identify and solve problems or faults', synonyms: ['debug', 'diagnose', 'resolve'], antonyms: ['ignore', 'neglect'], root: 'Modern English', family: ['troubleshooter', 'troubleshooting'], pos: 'verb', difficulty: 'intermediate', category: 'technical', techCategory: 'general', examples: ['Engineers troubleshoot server issues daily.', 'Learn to troubleshoot common errors.'] },
  { word: 'workflow', ipa: '/ˈwɜːrk.floʊ/', marathi: 'कार्यप्रवाह', hindi: 'कार्यप्रवाह', english: 'A sequence of processes through which work passes', synonyms: ['process', 'procedure', 'pipeline'], antonyms: [], root: 'Modern English', family: ['workflows'], pos: 'noun', difficulty: 'intermediate', category: 'technical', techCategory: 'general', examples: ['The CI/CD workflow automates deployments.', 'Optimize your development workflow.'] },
  { word: 'iterate', ipa: '/ˈɪt.ə.reɪt/', marathi: 'पुनरावृत्ती करणे', hindi: 'पुनरावृत्ति करना', english: 'To repeat a process, typically for improvement', synonyms: ['repeat', 'recur', 'reiterate'], antonyms: ['finalize', 'conclude'], root: 'Latin "iterare" meaning to repeat', family: ['iteration', 'iterative', 'iteratively'], pos: 'verb', difficulty: 'intermediate', category: 'technical', techCategory: 'general', examples: ['We iterate on the design based on feedback.', 'Agile development involves constant iteration.'] },
  { word: 'debug', ipa: '/diːˈbʌɡ/', marathi: 'डीबग करणे', hindi: 'डीबग करना', english: 'To identify and remove errors from code', synonyms: ['fix', 'correct', 'troubleshoot'], antonyms: ['break', 'introduce bugs'], root: 'Modern English (from "bug" in computing)', family: ['debugger', 'debugging'], pos: 'verb', difficulty: 'intermediate', category: 'technical', techCategory: 'backend', examples: ['Use console.log to debug your code.', 'The developer spent hours debugging the issue.'] },
  { word: 'deprecate', ipa: '/ˈdep.rə.keɪt/', marathi: 'अप्रचलित ठरवणे', hindi: 'अप्रचलित ठहराना', english: 'To express disapproval of; to declare something outdated', synonyms: ['disapprove', 'condemn', 'deplore'], antonyms: ['approve', 'endorse', 'support'], root: 'Latin "deprecatus" meaning to ward off', family: ['deprecation', 'deprecating'], pos: 'verb', difficulty: 'advanced', category: 'technical', examples: ['The committee deprecated the old standard.', 'We should deprecate this legacy feature.'] },
  { word: 'abstraction', ipa: '/æbˈstræk.ʃən/', marathi: 'अमूर्तीकरण', hindi: 'अमूर्तीकरण', english: 'The quality of dealing with ideas rather than events; hiding complexity', synonyms: ['generalization', 'simplification'], antonyms: ['concretization', 'specificity'], root: 'Latin "abstractus" meaning drawn away', family: ['abstract', 'abstractly'], pos: 'noun', difficulty: 'advanced', category: 'technical', techCategory: 'architecture', examples: ['Abstraction simplifies complex systems.', 'Good APIs provide clean abstraction layers.'] },
  { word: 'asynchronous', ipa: '/eɪˈsɪŋ.krə.nəs/', marathi: 'असिंक्रोनस', hindi: 'अतुल्यकालिक', english: 'Not existing or occurring at the same time; non-blocking', synonyms: ['non-blocking', 'concurrent'], antonyms: ['synchronous', 'blocking'], root: 'Greek "a-" meaning not + "synkhronos"', family: ['asynchrony', 'async'], pos: 'adjective', difficulty: 'advanced', category: 'technical', techCategory: 'backend', examples: ['Asynchronous programming improves performance.', 'JavaScript handles asynchronous operations well.'] },
  { word: 'bandwidth', ipa: '/ˈbænd.wɪdθ/', marathi: 'बँडविड्थ', hindi: 'बैंडविड्थ', english: 'The maximum rate of data transfer; capacity for work', synonyms: ['capacity', 'throughput', 'speed'], antonyms: [], root: 'Modern English', family: ['bandwidths'], pos: 'noun', difficulty: 'intermediate', category: 'technical', techCategory: 'devops', examples: ['The server has limited bandwidth.', 'We need more bandwidth for this task.'] },
  { word: 'bottleneck', ipa: '/ˈbɒt.əl.nek/', marathi: 'अडथळा', hindi: 'अड़चन', english: 'A point of congestion that slows down a system', synonyms: ['hindrance', 'obstacle', 'constraint'], antonyms: ['facilitator', 'accelerator'], root: 'Modern English', family: ['bottlenecks'], pos: 'noun', difficulty: 'intermediate', category: 'technical', techCategory: 'devops', examples: ['The database query is a bottleneck.', 'Identify and remove performance bottlenecks.'] },
  { word: 'cache', ipa: '/kæʃ/', marathi: 'कॅश', hindi: 'कैश', english: 'A storage layer that stores copies of data for faster access', synonyms: ['buffer', 'storage', 'reserve'], antonyms: [], root: 'French "cacher" meaning to hide', family: ['caching', 'cached'], pos: 'noun', difficulty: 'intermediate', category: 'technical', techCategory: 'backend', examples: ['Browser cache speeds up page loading.', 'Implement Redis cache for better performance.'] },
  { word: 'compliance', ipa: '/kəmˈplaɪ.əns/', marathi: 'अनुपालन', hindi: 'अनुपालन', english: 'The act of obeying rules, standards, or laws', synonyms: ['adherence', 'conformity', 'obedience'], antonyms: ['non-compliance', 'violation'], root: 'Latin "complere" meaning to fill up', family: ['compliant', 'comply'], pos: 'noun', difficulty: 'advanced', category: 'general', examples: ['The system must ensure data privacy compliance.', 'Regulatory compliance is mandatory.'] },
  { word: 'concurrency', ipa: '/kənˈkʌr.ən.si/', marathi: 'समवर्तीता', hindi: 'समवर्तीता', english: 'The ability of different parts of a system to run simultaneously', synonyms: ['parallelism', 'simultaneity'], antonyms: ['sequentiality'], root: 'Latin "concurrere" meaning to run together', family: ['concurrent', 'concurrently'], pos: 'noun', difficulty: 'advanced', category: 'technical', techCategory: 'backend', examples: ['Concurrency improves application performance.', 'Handle concurrency carefully to avoid race conditions.'] },
  { word: 'configuration', ipa: '/kənˌfɪɡ.əˈreɪ.ʃən/', marathi: 'कॉन्फिगरेशन', hindi: 'कॉन्फ़िगरेशन', english: 'The arrangement or setup of a system', synonyms: ['setup', 'arrangement', 'configuration'], antonyms: [], root: 'Latin "configurare" meaning to form after', family: ['configure', 'configurable'], pos: 'noun', difficulty: 'intermediate', category: 'technical', techCategory: 'devops', examples: ['The configuration file controls server settings.', 'Environment variables are used for configuration.'] },
  { word: 'dependency', ipa: '/dɪˈpen.dən.si/', marathi: 'अवलंबन', hindi: 'निर्भरता', english: 'A thing that relies on something else; a required component', synonyms: ['reliance', 'requirement', 'prerequisite'], antonyms: ['independence'], root: 'Latin "dependere" meaning to hang from', family: ['dependent', 'dependable'], pos: 'noun', difficulty: 'intermediate', category: 'technical', techCategory: 'backend', examples: ['The project has many dependencies.', 'Manage dependencies with a package manager.'] },
  { word: 'encryption', ipa: '/ɪnˈkrɪp.ʃən/', marathi: 'एन्क्रिप्शन', hindi: 'एन्क्रिप्शन', english: 'The process of encoding information securely', synonyms: ['encoding', 'scrambling', 'ciphering'], antonyms: ['decryption', 'decoding'], root: 'Greek "kryptos" meaning hidden', family: ['encrypt', 'encrypted'], pos: 'noun', difficulty: 'intermediate', category: 'technical', techCategory: 'security', examples: ['End-to-end encryption protects user data.', 'SSL encryption secures web traffic.'] },
  { word: 'latency', ipa: '/ˈleɪ.tən.si/', marathi: 'विलंब', hindi: 'विलंब', english: 'The delay before data transfer begins following an instruction', synonyms: ['delay', 'lag', 'downtime'], antonyms: ['speed', 'immediacy'], root: 'Latin "latens" meaning lying hidden', family: ['latent'], pos: 'noun', difficulty: 'intermediate', category: 'technical', techCategory: 'devops', examples: ['Low latency is critical for real-time apps.', 'Network latency affects user experience.'] },
  { word: 'microservice', ipa: '/ˈmaɪ.krəʊ.sɜːr.vɪs/', marathi: 'मायक्रोसर्व्हिस', hindi: 'माइक्रोसर्विस', english: 'An architectural style that structures an app as a collection of services', synonyms: ['service', 'module', 'component'], antonyms: ['monolith'], root: 'Modern English', family: ['microservices'], pos: 'noun', difficulty: 'advanced', category: 'technical', techCategory: 'architecture', examples: ['Microservices architecture enables independent deployment.', 'Each microservice handles a specific business function.'] },
  { word: 'monolith', ipa: '/ˈmɒn.ə.lɪθ/', marathi: 'मोनोलिथ', hindi: 'मोनोलिथ', english: 'A large single-piece structure; a monolithic application', synonyms: ['giant', 'colossus'], antonyms: ['microservice'], root: 'Greek "monos" meaning single + "lithos" stone', family: ['monolithic'], pos: 'noun', difficulty: 'advanced', category: 'technical', techCategory: 'architecture', examples: ['The monolith was broken into microservices.', 'Monolithic applications are harder to scale.'] },
  { word: 'orchestration', ipa: '/ˌɔːr.kɪˈstreɪ.ʃən/', marathi: 'ऑर्केस्ट्रेशन', hindi: 'ऑर्केस्ट्रेशन', english: 'The automated arrangement and management of complex systems', synonyms: ['coordination', 'management', 'organization'], antonyms: ['chaos', 'disorganization'], root: 'Greek "orcheisthai" meaning to dance', family: ['orchestrate', 'orchestrator'], pos: 'noun', difficulty: 'advanced', category: 'technical', techCategory: 'devops', examples: ['Kubernetes provides container orchestration.', 'Service orchestration automates workflows.'] },
  { word: 'provision', ipa: '/prəˈvɪʒ.ən/', marathi: 'पुरवठा करणे', hindi: 'प्रावधान करना', english: 'To supply or provide resources or services', synonyms: ['supply', 'provide', 'furnish'], antonyms: ['withhold', 'deprive'], root: 'Latin "provisio" meaning foresight', family: ['provisioning', 'provisional'], pos: 'verb', difficulty: 'intermediate', category: 'technical', techCategory: 'devops', examples: ['Provision new servers automatically.', 'Cloud resources are provisioned on demand.'] },
  { word: 'repository', ipa: '/rɪˈpɒz.ɪ.tər.i/', marathi: 'भांडार', hindi: 'भंडार', english: 'A central location where data or code is stored', synonyms: ['archive', 'storage', 'storehouse'], antonyms: [], root: 'Latin "repositorium" meaning store', family: ['repositories'], pos: 'noun', difficulty: 'intermediate', category: 'technical', techCategory: 'general', examples: ['Git repositories store version control data.', 'The code repository is hosted on GitHub.'] },
  { word: 'throughput', ipa: '/ˈθruː.pʊt/', marathi: 'थ्रूपुट', hindi: 'थ्रूपुट', english: 'The amount of material or data processed in a given time', synonyms: ['output', 'capacity', 'volume'], antonyms: ['bottleneck', 'limitation'], root: 'Modern English', family: ['throughputs'], pos: 'noun', difficulty: 'intermediate', category: 'technical', techCategory: 'devops', examples: ['The system handles high throughput.', 'Monitor throughput to identify performance issues.'] },
];

async function seed() {
  const connection = await mysql.createConnection({
    host: process.env.DB_HOST,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    port: parseInt(process.env.DB_PORT) || 3306
  });

  try {
    console.log('🌱 Seeding database...');

    const [existing] = await connection.execute('SELECT COUNT(*) as cnt FROM words');
    if (existing[0].cnt > 0) {
      console.log('📦 Words already seeded, skipping...');
    } else {
      for (const w of words) {
        await connection.execute(
          `INSERT INTO words (id, word, ipa_pronunciation, marathi_meaning, hindi_meaning,
            english_meaning, synonyms, antonyms, root_word, word_family, difficulty,
            part_of_speech, category, technical_category, examples, frequency)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
          [
            uuidv4(), w.word, w.ipa, w.marathi, w.hindi, w.english,
            JSON.stringify(w.synonyms), JSON.stringify(w.antonyms),
            w.root, JSON.stringify(w.family), w.difficulty,
            w.pos, w.category, w.techCategory || null,
            JSON.stringify(w.examples || []),
            Math.floor(Math.random() * 100) + 1
          ]
        );
      }
      console.log(`✅ ${words.length} words seeded`);
    }

    console.log('🎉 Seed complete!');
  } catch (error) {
    console.error('❌ Seed error:', error.message);
    throw error;
  } finally {
    await connection.end();
  }
}

seed()
  .then(() => process.exit(0))
  .catch(() => process.exit(1));
