import { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Search, BookOpen, X, Clock, AlertCircle,
  Loader2, Volume2, ChevronRight, BookMarked, Trash2, Sparkles
} from 'lucide-react';
import toast from 'react-hot-toast';
import * as wordsApi from '../../api/words';

const statusOptions = [
  { value: 'all', label: 'All', color: 'text-gray-400' },
  { value: 'learning', label: 'Learning', color: 'text-yellow-400' },
  { value: 'revision', label: 'Revision', color: 'text-purple-400' },
  { value: 'mastered', label: 'Mastered', color: 'text-green-400' },
  { value: 'longterm', label: 'Long Term', color: 'text-blue-400' },
];

const statusBadge = {
  learning: 'badge-amber',
  revision: 'badge-purple',
  mastered: 'badge-green',
  longterm: 'badge-blue',
};

const tenseLabels = {
  simplePresent: 'Simple Present',
  presentContinuous: 'Present Continuous',
  presentPerfect: 'Present Perfect',
  simplePast: 'Simple Past',
  pastContinuous: 'Past Continuous',
  pastPerfect: 'Past Perfect',
  simpleFuture: 'Simple Future',
  futureContinuous: 'Future Continuous',
  futurePerfect: 'Future Perfect',
};

function ShimmerBlock({ className }) {
  return <div className={`skeleton rounded-xl ${className}`} />;
}

function SentenceModal({ word, onClose }) {
  const [sentences, setSentences] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [activeTense, setActiveTense] = useState('simplePresent');

  const loadSentences = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await wordsApi.generateSentences(word);
      setSentences(data.sentences);
    } catch (err) {
      setError(err?.error || 'Failed to generate sentences');
    } finally {
      setLoading(false);
    }
  };

  if (!sentences && !loading && !error) {
    loadSentences();
  }

  const tenseKeys = sentences ? Object.keys(tenseLabels).filter((k) => sentences[k]) : [];

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
      onClick={onClose}
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.92, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.92, y: 20 }}
        transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
        className="relative w-full max-w-2xl max-h-[85vh] overflow-y-auto glass-strong p-6 sm:p-8"
        onClick={(e) => e.stopPropagation()}
      >
        <button
          onClick={onClose}
          className="absolute top-4 right-4 w-8 h-8 rounded-lg flex items-center justify-center text-gray-500 hover:text-white hover:bg-white/5 transition-all"
        >
          <X size={18} />
        </button>

        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500/20 to-purple-600/10 border border-purple-500/20 flex items-center justify-center shrink-0">
            <Sparkles size={20} className="text-purple-400" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white">"{word}" — Sentences</h2>
            <p className="text-xs text-gray-500 mt-0.5">Generated by AI across 9 tenses</p>
          </div>
        </div>

        {loading && (
          <div className="flex items-center justify-center py-16">
            <div className="text-center">
              <Loader2 size={28} className="animate-spin text-purple-400 mx-auto mb-3" />
              <p className="text-sm text-gray-400">Generating sentences...</p>
            </div>
          </div>
        )}

        {error && (
          <div className="glass-card p-6 text-center">
            <AlertCircle size={24} className="text-red-400 mx-auto mb-2" />
            <p className="text-sm text-gray-400 mb-3">{error}</p>
            <button onClick={loadSentences} className="btn-premium text-sm">Try Again</button>
          </div>
        )}

        {sentences && !loading && (
          <>
            <div className="flex gap-1.5 overflow-x-auto scrollbar-hide mb-5 pb-1 flex-wrap">
              {tenseKeys.map((key) => (
                <button
                  key={key}
                  onClick={() => setActiveTense(key)}
                  className={`px-2.5 py-1 rounded-lg text-[11px] font-medium border whitespace-nowrap transition-all ${
                    activeTense === key
                      ? 'bg-purple-500/15 text-purple-400 border-purple-500/30'
                      : 'text-gray-500 border-white/5 hover:text-white hover:bg-white/5'
                  }`}
                >
                  {tenseLabels[key]}
                </button>
              ))}
            </div>

            <AnimatePresence mode="wait">
              <motion.div
                key={activeTense}
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -8 }}
                transition={{ duration: 0.2 }}
              >
                <p className="text-xs text-gray-500 uppercase tracking-wider mb-3 font-medium">{tenseLabels[activeTense]}</p>
                <div className="space-y-2.5">
                  {sentences[activeTense]?.map((s, i) => (
                    <div key={i} className="p-3 rounded-xl bg-white/5 border border-white/10">
                      <p className="text-sm text-white leading-relaxed">{s.english}</p>
                      <p className="text-xs text-purple-300 mt-1.5">{s.marathi}</p>
                    </div>
                  ))}
                </div>
              </motion.div>
            </AnimatePresence>

            <div className="mt-5 pt-4 border-t border-white/5 flex items-center justify-between text-xs text-gray-500">
              <span>{tenseKeys.length} tenses &middot; {(sentences[activeTense]?.length || 0)} sentences</span>
              <button
                onClick={loadSentences}
                className="flex items-center gap-1 hover:text-white transition-colors"
              >
                <Loader2 size={11} />
                Regenerate
              </button>
            </div>
          </>
        )}
      </motion.div>
    </motion.div>
  );
}

function EmptyState({ search, status }) {
  return (
    <div className="col-span-full glass-card p-12 text-center">
      <div className="w-16 h-16 mx-auto mb-4 rounded-2xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center">
        <BookMarked size={32} className="text-purple-400" />
      </div>
      <h3 className="text-lg font-bold text-white mb-1">
        {search ? 'No matching words' : 'No words yet'}
      </h3>
      <p className="text-sm text-gray-400 mb-4">
        {search
          ? `No words match "${search}"`
          : status !== 'all'
            ? `No words with status "${status}"`
            : 'Learn new words to build your vocabulary'}
      </p>
    </div>
  );
}

export default function MyWordsPage() {
  const [statusFilter, setStatusFilter] = useState('all');
  const [search, setSearch] = useState('');
  const [sentenceWord, setSentenceWord] = useState(null);
  const [deletingId, setDeletingId] = useState(null);

  const queryParams = useMemo(() => {
    const params = {};
    if (statusFilter !== 'all') params.status = statusFilter;
    return params;
  }, [statusFilter]);

  const { data: rawData, isLoading, error, refetch } = useQuery({
    queryKey: ['my-words', queryParams],
    queryFn: () => wordsApi.getMyVocabulary(queryParams),
    retry: 1,
    staleTime: 30000,
  });

  const words = useMemo(() => rawData?.words || [], [rawData]);
  const queryError = error?.message || '';

  const handleDelete = async (wordId, e) => {
    e.stopPropagation();
    if (!window.confirm('Remove this word from your vocabulary?')) return;
    setDeletingId(wordId);
    try {
      await wordsApi.removeFromVocabulary(wordId);
      toast.success('Word removed from vocabulary');
      refetch();
    } catch (err) {
      toast.error(err?.error || 'Failed to remove word');
    } finally {
      setDeletingId(null);
    }
  };

  const filteredWords = useMemo(() => {
    let result = [...words];

    if (search.trim()) {
      const q = search.toLowerCase();
      result = result.filter(
        (w) =>
          w.word?.toLowerCase().includes(q) ||
          w.english_meaning?.toLowerCase().includes(q) ||
          w.marathi_meaning?.toLowerCase().includes(q) ||
          w.hindi_meaning?.toLowerCase().includes(q)
      );
    }

    return result;
  }, [words, search]);

  if (isLoading) {
    return (
      <div className="p-6 max-w-6xl mx-auto space-y-6 anim-fade-in-up">
        <div className="flex items-center justify-between">
          <div>
            <ShimmerBlock className="h-8 w-40" />
            <ShimmerBlock className="h-4 w-24 mt-2" />
          </div>
          <ShimmerBlock className="h-10 w-64" />
        </div>
        <ShimmerBlock className="h-12 w-full" />
        <div className="space-y-3">
          {Array.from({ length: 5 }, (_, i) => (
            <ShimmerBlock key={i} className="h-16 w-full" />
          ))}
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-6 max-w-4xl mx-auto anim-fade-in-up">
        <div className="glass-card p-12 text-center">
          <div className="w-16 h-16 mx-auto mb-4 rounded-2xl bg-red-500/10 border border-red-500/20 flex items-center justify-center">
            <AlertCircle size={32} className="text-red-400" />
          </div>
          <h2 className="text-xl font-bold text-white mb-2">Failed to Load</h2>
          <p className="text-gray-400 mb-6">{queryError}</p>
          <button onClick={() => refetch()} className="btn-premium">Try Again</button>
        </div>
      </div>
    );
  }

  return (
    <div className="p-6 max-w-6xl mx-auto space-y-6">
      <AnimatePresence>
        {sentenceWord && (
          <SentenceModal
            word={sentenceWord}
            onClose={() => setSentenceWord(null)}
          />
        )}
      </AnimatePresence>

      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gradient">My Words</h1>
          <p className="text-sm text-gray-400 mt-1">
            {words.length} word{words.length !== 1 ? 's' : ''} in your vocabulary
          </p>
        </div>
        <div className="relative">
          <Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-500 pointer-events-none" />
          <input
            type="text"
            placeholder="Search words..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="input-premium pl-9 pr-9 w-64 text-sm"
          />
          {search && (
            <button
              onClick={() => setSearch('')}
              className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-white transition-colors"
            >
              <X size={14} />
            </button>
          )}
        </div>
      </div>

      <div className="flex items-center gap-2 overflow-x-auto scrollbar-hide">
        {statusOptions.map((opt) => (
          <button
            key={opt.value}
            onClick={() => setStatusFilter(opt.value)}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-medium border transition-all whitespace-nowrap ${
              statusFilter === opt.value
                ? 'bg-purple-500/15 text-purple-400 border-purple-500/30'
                : 'text-gray-400 border-white/5 hover:text-white hover:bg-white/5'
            }`}
          >
            {opt.label}
          </button>
        ))}
      </div>

      {filteredWords.length === 0 ? (
        <EmptyState search={search} status={statusFilter} />
      ) : (
        <div className="space-y-2">
          <AnimatePresence>
            {filteredWords.map((word, i) => (
              <motion.div
                key={word.id || word.word_id || i}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.2, delay: i * 0.03 }}
                onClick={() => setSentenceWord(word.word)}
                className="glass-card hover-lift p-4 flex items-center gap-4 cursor-pointer group"
              >
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500/20 to-purple-600/10 border border-purple-500/20 flex items-center justify-center shrink-0">
                  <BookOpen size={18} className="text-purple-400" />
                </div>

                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-0.5">
                    <span className="text-sm font-semibold text-white group-hover:text-purple-400 transition-colors">
                      {word.word}
                    </span>
                    <span className={`badge ${statusBadge[word.status] || 'bg-white/5 text-gray-400 border-white/10'}`}>
                      {word.status || 'unknown'}
                    </span>
                  </div>

                  {word.marathi_meaning && (
                    <p className="text-xs text-purple-300/80 font-medium">
                      {word.marathi_meaning}
                    </p>
                  )}

                  {word.english_meaning && (
                    <p className="text-xs text-gray-500 mt-0.5 line-clamp-1">
                      {word.english_meaning}
                    </p>
                  )}

                  {word.next_revision && (
                    <div className="flex items-center gap-1 mt-1.5">
                      <Clock size={10} className="text-gray-600" />
                      <span className={`text-[10px] ${
                        new Date(word.next_revision) < new Date()
                          ? 'text-red-400'
                          : 'text-gray-500'
                      }`}>
                        Next: {word.next_revision ? (() => {
                          const d = new Date(word.next_revision);
                          const now = new Date();
                          const diff = d - now;
                          const days = Math.round(diff / (1000 * 60 * 60 * 24));
                          if (days < 0) return 'Overdue';
                          if (days === 0) return 'Today';
                          if (days === 1) return 'Tomorrow';
                          return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
                        })() : '—'}
                      </span>
                    </div>
                  )}
                </div>

                <div className="flex items-center gap-1 shrink-0">
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      if ('speechSynthesis' in window) {
                        const u = new SpeechSynthesisUtterance(word.word);
                        u.lang = 'en-US';
                        speechSynthesis.cancel();
                        speechSynthesis.speak(u);
                      }
                    }}
                    className="w-8 h-8 rounded-lg flex items-center justify-center text-gray-500 hover:text-purple-400 hover:bg-purple-500/10 transition-all"
                  >
                    <Volume2 size={15} />
                  </button>
                  <button
                    onClick={(e) => handleDelete(word.word_id, e)}
                    disabled={deletingId === word.word_id}
                    className="w-8 h-8 rounded-lg flex items-center justify-center text-red-400/50 hover:text-red-400 hover:bg-red-500/10 transition-all disabled:opacity-40"
                  >
                    {deletingId === word.word_id ? <Loader2 size={14} className="animate-spin" /> : <Trash2 size={14} />}
                  </button>
                  <ChevronRight size={16} className="text-gray-600 group-hover:text-purple-400 transition-colors ml-1" />
                </div>
              </motion.div>
            ))}
          </AnimatePresence>
        </div>
      )}

      {!isLoading && words.length > 0 && (
        <div className="flex items-center justify-between text-xs text-gray-500 pt-2">
          <span>Showing {filteredWords.length} of {words.length} words</span>
          <button
            onClick={() => refetch()}
            className="flex items-center gap-1 hover:text-white transition-colors"
          >
            <Loader2 size={12} />
            Refresh
          </button>
        </div>
      )}
    </div>
  );
}
